import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import { changeCurrency } from "@/redux/slices/currencySlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const currency = useSelector((state: RootState) => state.currency.value);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button
            aria-label="Change currency"
            onClick={() => dispatch(changeCurrency("GBP"))}
          >
            USD
          </button>
          <div>{currency}</div>
        </div>
      </main>
    </>
  );
}
