name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # Runs tests in parallel with matrix strategy
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build # Add this step to build the Next.js app

      - name: Start server
        run: npm start

      - name: Wait for server to be ready
        run: |
          while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000)" != "200" ]; do sleep 5; done

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: '' # Leave this empty as we've already started the server
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
